name: CI

on: pull_request_review

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Test
      id: test
      uses: NitorCreations/account-vending-machine@master
      env:
        APPROVALS: "2"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION:   eu-north-1
